#pragma once
#include <Core.h>
#include <Utils/StrongTypedef.h>
#include "../RenderStates.h"

namespace Renderer
{
    enum ImageFormat 
    {
        IMAGE_FORMAT_UNKNOWN,
        IMAGE_FORMAT_R32G32B32A32_TYPELESS,
        IMAGE_FORMAT_R32G32B32A32_FLOAT,
        IMAGE_FORMAT_R32G32B32A32_UINT,
        IMAGE_FORMAT_R32G32B32A32_SINT,
        IMAGE_FORMAT_R32G32B32_TYPELESS,
        IMAGE_FORMAT_R32G32B32_FLOAT,
        IMAGE_FORMAT_R32G32B32_UINT,
        IMAGE_FORMAT_R32G32B32_SINT,
        IMAGE_FORMAT_R16G16B16A16_TYPELESS,
        IMAGE_FORMAT_R16G16B16A16_FLOAT,
        IMAGE_FORMAT_R16G16B16A16_UNORM,
        IMAGE_FORMAT_R16G16B16A16_UINT,
        IMAGE_FORMAT_R16G16B16A16_SNORM,
        IMAGE_FORMAT_R16G16B16A16_SINT,
        IMAGE_FORMAT_R32G32_TYPELESS,
        IMAGE_FORMAT_R32G32_FLOAT,
        IMAGE_FORMAT_R32G32_UINT,
        IMAGE_FORMAT_R32G32_SINT,
        IMAGE_FORMAT_R10G10B10A2_TYPELESS,
        IMAGE_FORMAT_R10G10B10A2_UNORM,
        IMAGE_FORMAT_R10G10B10A2_UINT,
        IMAGE_FORMAT_R11G11B10_FLOAT,
        IMAGE_FORMAT_R8G8B8A8_TYPELESS,
        IMAGE_FORMAT_R8G8B8A8_UNORM,
        IMAGE_FORMAT_R8G8B8A8_UNORM_SRGB,
        IMAGE_FORMAT_R8G8B8A8_UINT,
        IMAGE_FORMAT_R8G8B8A8_SNORM,
        IMAGE_FORMAT_R8G8B8A8_SINT,
        IMAGE_FORMAT_R16G16_TYPELESS,
        IMAGE_FORMAT_R16G16_FLOAT,
        IMAGE_FORMAT_R16G16_UNORM,
        IMAGE_FORMAT_R16G16_UINT,
        IMAGE_FORMAT_R16G16_SNORM,
        IMAGE_FORMAT_R16G16_SINT,
        IMAGE_FORMAT_R32_TYPELESS,
        IMAGE_FORMAT_R32_FLOAT,
        IMAGE_FORMAT_R32_UINT,
        IMAGE_FORMAT_R32_SINT,
        IMAGE_FORMAT_R24G8_TYPELESS,
        IMAGE_FORMAT_R8G8_TYPELESS,
        IMAGE_FORMAT_R8G8_UNORM,
        IMAGE_FORMAT_R8G8_UINT,
        IMAGE_FORMAT_R8G8_SNORM,
        IMAGE_FORMAT_R8G8_SINT,
        IMAGE_FORMAT_R16_TYPELESS,
        IMAGE_FORMAT_R16_FLOAT,
        IMAGE_FORMAT_D16_UNORM,
        IMAGE_FORMAT_R16_UNORM,
        IMAGE_FORMAT_R16_UINT,
        IMAGE_FORMAT_R16_SNORM,
        IMAGE_FORMAT_R16_SINT,
        IMAGE_FORMAT_R8_TYPELESS,
        IMAGE_FORMAT_R8_UNORM,
        IMAGE_FORMAT_R8_UINT,
        IMAGE_FORMAT_R8_SNORM,
        IMAGE_FORMAT_R8_SINT,
        IMAGE_FORMAT_A8_UNORM,
        IMAGE_FORMAT_R1_UNORM
    };

    struct ImageDesc
    {
        Vector2i dimensions;
        ImageFormat format = IMAGE_FORMAT_UNKNOWN;
        SampleCount sampleCount;
    };

    // Lets strong-typedef an ID type with the underlying type of u16
    STRONG_TYPEDEF(ImageID, u16);
}